version: "3.7"
services:
  api_service:
    env_file:
      - .env.${DOCKER_ENV:-dev}
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/${MYSQL_DATABASE:-vollmed_api}
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-vollmed_api}
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net: