name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Run Tests
      run: docker-compose run --rm app mvn test -B

    - name: Tear down Docker Compose
      run: docker-compose down
